
package ehealth.model.bl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PeopleBL", targetNamespace = "http://bl.model.ehealth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeopleBL {


    /**
     * 
     * @return
     *     returns java.util.List<ehealth.model.bl.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonListResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/readPersonListRequest", output = "http://bl.model.ehealth/PeopleBL/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param idPerson
     * @return
     *     returns ehealth.model.bl.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/readPersonRequest", output = "http://bl.model.ehealth/PeopleBL/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.UpdatePersonResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/updatePersonRequest", output = "http://bl.model.ehealth/PeopleBL/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns ehealth.model.bl.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.CreatePersonResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/createPersonRequest", output = "http://bl.model.ehealth/PeopleBL/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.DeletePersonResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/deletePersonRequest", output = "http://bl.model.ehealth/PeopleBL/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "measureTypes", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadMeasureTypesResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/readMeasureTypesRequest", output = "http://bl.model.ehealth/PeopleBL/readMeasureTypesResponse")
    public List<String> readMeasureTypes();

    /**
     * 
     * @param idPerson
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.model.bl.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonHistoryResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/readPersonHistoryRequest", output = "http://bl.model.ehealth/PeopleBL/readPersonHistoryResponse")
    public List<HealthMeasureHistory> readPersonHistory(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param idPerson
     * @param mid
     * @param measureType
     * @return
     *     returns ehealth.model.bl.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.ReadPersonMeasureResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/readPersonMeasureRequest", output = "http://bl.model.ehealth/PeopleBL/readPersonMeasureResponse")
    public HealthMeasureHistory readPersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "mid", targetNamespace = "")
        Long mid);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.model.bl.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.SavePersonMeasureResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/savePersonMeasureRequest", output = "http://bl.model.ehealth/PeopleBL/savePersonMeasureResponse")
    public HealthMeasureHistory savePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.model.bl.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://bl.model.ehealth/", className = "ehealth.model.bl.UpdatePersonMeasureResponse")
    @Action(input = "http://bl.model.ehealth/PeopleBL/updatePersonMeasureRequest", output = "http://bl.model.ehealth/PeopleBL/updatePersonMeasureResponse")
    public HealthMeasureHistory updatePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

}
